### ISSUE TITLE
problems in train.py

### ISSUE THREAD

**Issue by YUDASHUAI916** [whai362/pan_pp.pytorch#16]
Hi. When I run 'python train.py config/pan/pan_r18_ic15.py' , the errors are as followings:
 Do you know how to solve the problem? Thank you very much.
Traceback (most recent call last):
  File "train.py", line 234, in <module>
    main(args)
  File "train.py", line 216, in main
    train(train_loader, model, optimizer, epoch, start_iter, cfg)
  File "train.py", line 41, in train
    for iter, data in enumerate(train_loader):
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 435, in __next__
    data = self._next_data()
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "D:\Anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1111, in _process_data
    data.reraise()
  File "D:\Anaconda3\lib\site-packages\torch\_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: function takes exactly 5 arguments (1 given)

**Comment by whai362** [comment]
It may be the problem of software environment.

**Comment by qqqqq127** [comment]
same problem.
