### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'resume'

### ISSUE THREAD

**Issue by seekingdeep** [whai362/pan_pp.pytorch#32]
An error appears when trying to test the model:
```
(pan) home@home-lnx:~/programs/pan_pp.pytorch$ python test.py config/pan/pan_r18_ic15.py checkpoints/pan_r18_ic15/checkpoint.pth.tar
{
    "model": {
        "type": "PAN",
        "backbone": {
            "type": "resnet18",
            "pretrained": true
        },
        "neck": {
            "type": "FPEM_v1",
            "in_channels": [
                64,
                128,
                256,
                512
            ],
            "out_channels": 128
        },
        "detection_head": {
            "type": "PA_Head",
            "in_channels": 512,
            "hidden_dim": 128,
            "num_classes": 6,
            "loss_text": {
                "type": "DiceLoss",
                "loss_weight": 1.0
            },
            "loss_kernel": {
                "type": "DiceLoss",
                "loss_weight": 0.5
            },
            "loss_emb": {
                "type": "EmbLoss_v1",
                "feature_dim": 4,
                "loss_weight": 0.25
            }
        }
    },
    "data": {
        "batch_size": 16,
        "train": {
            "type": "PAN_IC15",
            "split": "train",
            "is_transform": true,
            "img_size": 736,
            "short_size": 736,
            "kernel_scale": 0.5,
            "read_type": "cv2"
        },
        "test": {
            "type": "PAN_IC15",
            "split": "test",
            "short_size": 736,
            "read_type": "cv2",
            "report_speed": false
        }
    },
    "train_cfg": {
        "lr": 0.001,
        "schedule": "polylr",
        "epoch": 600,
        "optimizer": "Adam"
    },
    "test_cfg": {
        "min_score": 0.85,
        "min_area": 16,
        "bbox_type": "rect",
        "result_path": "outputs/submit_ic15.zip"
    },
    "report_speed": false
}
Downloading: "http://sceneparsing.csail.mit.edu/model/pretrained_resnet/resnet18-imagenet.pth" to ./pretrained/resnet18-imagenet.pth
Traceback (most recent call last):
  File "test.py", line 117, in <module>
    main(args)
  File "test.py", line 100, in main
    print("No checkpoint found at '{}'".format(args.resume))
AttributeError: 'Namespace' object has no attribute 'resume'
```

**Comment by WeichangChen2020** [comment]
这个怎么解决的啊

**Comment by WeichangChen2020** [comment]
How can I fix this problem
