### ISSUE TITLE
训练Total Text时遇到的问题

### ISSUE THREAD

**Issue by mashumli** [whai362/pan_pp.pytorch#44]
运行 python train.py config/pan/pan_r18_tt.py 后，出现如下情况：
![p1](https://user-images.githubusercontent.com/84255685/121690279-3bdd6f80-caf8-11eb-8fe4-5e57bbe1a68c.png)
Traceback (most recent call last):
  File "/home/dell2/anaconda3/envs/pannet/lib/python3.6/multiprocessing/queues.py", line 234, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/dell2/anaconda3/envs/pannet/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'cPolygon.Error'>: import of module 'cPolygon' failed
似乎是迭代过程中出现的问题且只出现在训练TT数据集的时候
请问出现这种情况该怎样解决呢？谢谢您

**Comment by czczup** [comment]
没有遇到过这个问题，你安装的Polygon是什么版本？

**Comment by guoli188** [comment]
我也遇到了这个问题，请问解决了吗，我按照 的Polygon 3.0.9.1
